/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pilot/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Get current pilot configuration
         *
         *     Returns:
         *         dict: Current configuration
         */
        get: operations["get_config_api_pilot_config_get"];
        put?: never;
        /**
         * Update Config
         * @description Update pilot configuration
         *
         *     Args:
         *         config: New configuration
         *
         *     Returns:
         *         dict: Status message
         */
        post: operations["update_config_api_pilot_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Get pilot statistics
         *
         *     Returns:
         *         dict: Current stats (active tasks, pending downloads, disk usage, totals, run times)
         */
        get: operations["get_stats_api_pilot_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dry Run
         * @description Simulate run - returns what would be downloaded/cleaned
         *
         *     Returns:
         *         dict: Download candidates and cleanup candidates
         */
        get: operations["dry_run_api_pilot_dry_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/run-download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Download
         * @description Manually trigger download cycle
         *
         *     Returns:
         *         dict: Status message
         */
        post: operations["trigger_download_api_pilot_run_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/run-cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Cleanup
         * @description Manually trigger cleanup cycle
         *
         *     Returns:
         *         dict: Status message
         */
        post: operations["trigger_cleanup_api_pilot_run_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/media-wall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Home Media Wall
         * @description Return the cached Home media wall snapshot without refreshing M-Team.
         */
        get: operations["get_home_media_wall_api_home_media_wall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/panel/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Panel Stats
         * @description 获取实时统计数据
         */
        get: operations["get_panel_stats_api_panel_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/panel/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Panel History
         * @description 获取流量历史数据
         *
         *     Args:
         *         range: 时间范围，可选值: 1h, 6h, 12h, 24h, 7d, 30d
         *
         *     Returns:
         *         {
         *             "range": "24h",
         *             "aggregation": "5min",
         *             "data_points": [...]
         *         }
         */
        get: operations["get_panel_history_api_panel_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/panel/share-ratio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Panel Share Ratio
         * @description 获取分享率历史数据
         *
         *     Args:
         *         range: 时间范围，可选值: 1h, 6h, 12h, 24h, 7d, 30d
         *
         *     Returns:
         *         {
         *             "range": "24h",
         *             "data_points": [...],
         *             "current": 1.23,
         *             "highest": 1.50,
         *             "lowest": 1.00,
         *             "change_24h": 0.05
         *         }
         */
        get: operations["get_panel_share_ratio_api_panel_share_ratio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/panel/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Panel Torrents
         * @description 获取种子列表（带筛选）
         *
         *     Args:
         *         tag: 标签筛选 ("声呐做种" | "雷达下载" | "PILOT")
         *         status: 状态筛选 ("downloading" | "seeding" | "paused" | "completed")
         *
         *     Returns:
         *         {
         *             "torrents": List[Dict],
         *             "total_count": int,
         *             "filtered_count": int
         *         }
         */
        get: operations["get_panel_torrents_api_panel_torrents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/panel/torrents/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Torrents
         * @description 批量暂停种子
         */
        post: operations["pause_torrents_api_panel_torrents_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/panel/torrents/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Torrents
         * @description 批量恢复种子
         */
        post: operations["resume_torrents_api_panel_torrents_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/panel/torrents/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Torrents
         * @description 批量删除种子
         */
        post: operations["delete_torrents_api_panel_torrents_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Torrents
         * @description 获取种子列表
         */
        get: operations["get_torrents_api_torrents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description 手动触发刷新
         */
        post: operations["refresh_api_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Torrent
         * @description 从 Free Hunter 下载种子
         */
        post: operations["download_torrent_api_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auto-delete/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Delete Toggle
         * @description 切换自动删除功能
         */
        post: operations["auto_delete_toggle_api_auto_delete_toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auto-delete/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auto Delete Status
         * @description 获取自动删除功能状态
         */
        get: operations["auto_delete_status_api_auto_delete_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Categories
         * @description 获取类别列表
         */
        get: operations["categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter Options
         * @description 获取搜索筛选选项
         */
        get: operations["filter_options_api_filter_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Radar
         * @description 雷达搜索种子
         */
        post: operations["radar_api_radar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Radar Download
         * @description 从雷达结果下载种子
         */
        post: operations["radar_download_api_radar_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查接口
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Status
         * @description 运行时状态：缓存、依赖和非敏感配置
         */
        get: operations["api_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiStatusResponse
         * @description Runtime status response
         */
        ApiStatusResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Commit */
            commit: string;
            /** Timestamp */
            timestamp: string;
            cache: components["schemas"]["CacheStatus"];
            panel_collector: components["schemas"]["PanelCollectorStatus"];
            /** Dependencies */
            dependencies: {
                [key: string]: components["schemas"]["DependencyStatusResponse"];
            };
            config: components["schemas"]["RuntimeConfigStatus"];
            /**
             * Warnings
             * @default []
             */
            warnings?: string[];
        };
        /**
         * AutoDeleteToggleRequest
         * @description Request model for auto-delete toggle (idempotent set)
         */
        AutoDeleteToggleRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * AutomationConfig
         * @description Main pilot configuration (credentials via env vars, not stored)
         */
        AutomationConfig: {
            download?: components["schemas"]["DownloadPolicy"];
            cleanup?: components["schemas"]["CleanupPolicy"];
            /**
             * Enable Notification
             * @default true
             */
            enable_notification?: boolean;
        };
        /**
         * CacheStatus
         * @description Runtime cache status exposed by /api/status
         */
        CacheStatus: {
            /** Last Update */
            last_update?: string | null;
            /** Last Success */
            last_success?: string | null;
            /** Next Refresh */
            next_refresh?: string | null;
            /** Age Seconds */
            age_seconds?: number | null;
            /**
             * Stale
             * @default false
             */
            stale?: boolean;
            /**
             * Stale After Seconds
             * @default 0
             */
            stale_after_seconds?: number;
            /**
             * Total
             * @default 0
             */
            total?: number;
            /** Error */
            error?: string | null;
            /** Last Error */
            last_error?: string | null;
        };
        /**
         * CleanupPolicy
         * @description Cleanup policy configuration
         */
        CleanupPolicy: {
            /**
             * Enabled
             * @default true
             */
            enabled?: boolean;
            /**
             * Min Share Ratio
             * @default 0
             */
            min_share_ratio?: number;
            /**
             * Min Seed Time Hours
             * @default 1
             */
            min_seed_time_hours?: number;
            /**
             * Max Download Time Hours
             * @default 12
             */
            max_download_time_hours?: number;
            /**
             * Dead Seed Minutes
             * @default 30
             */
            dead_seed_minutes?: number;
            /**
             * Dead Seed Max Ratio
             * @default 0.01
             */
            dead_seed_max_ratio?: number;
            /**
             * Min Current Users
             * @default 5
             */
            min_current_users?: number;
            /**
             * Min Upload Speed Kbps
             * @default 200
             */
            min_upload_speed_kbps?: number;
            /**
             * Elimination Ratio
             * @default 0
             */
            elimination_ratio?: number;
        };
        /** DeleteTorrentsRequest */
        DeleteTorrentsRequest: {
            /** Hashes */
            hashes: string[];
            /**
             * Delete Files
             * @default true
             */
            delete_files?: boolean;
        };
        /**
         * DependencyStatusResponse
         * @description External dependency status exposed by /api/status
         */
        DependencyStatusResponse: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Last Success */
            last_success?: string | null;
            /** Last Error */
            last_error?: string | null;
        };
        /**
         * DownloadPolicy
         * @description Download policy configuration
         */
        DownloadPolicy: {
            /**
             * Enabled
             * @default true
             */
            enabled?: boolean;
            /**
             * Max Active Tasks
             * @default 20
             */
            max_active_tasks?: number;
            /**
             * Interval Seconds
             * @default 300
             */
            interval_seconds?: number;
            /**
             * Save Path
             * @default /downloads/mt_free_farm
             */
            save_path?: string;
            /**
             * Disk Usage Threshold
             * @default 90
             */
            disk_usage_threshold?: number;
            rules?: components["schemas"]["RuleConfig"];
        };
        /**
         * DownloadRequest
         * @description Request model for torrent download
         */
        DownloadRequest: {
            /** Id */
            id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MediaWallItem
         * @description Single read-only item displayed in the Home media wall
         */
        MediaWallItem: {
            /** Id */
            id: string;
            /** Media Key */
            media_key: string;
            /** Title */
            title: string;
            /** Torrent Name */
            torrent_name: string;
            /** Poster Url */
            poster_url?: string | null;
            /**
             * Detail Url
             * @default
             */
            detail_url?: string;
            /**
             * Year
             * @default
             */
            year?: string;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "series" | "other";
            /** Episode */
            episode?: string | null;
            /** Quality Tags */
            quality_tags?: string[];
            /**
             * Rail Reason
             * @default
             */
            rail_reason?: string;
            /**
             * Created Date
             * @default
             */
            created_date?: string;
            /**
             * Size
             * @default 0
             */
            size?: number;
            /**
             * Size Display
             * @default
             */
            size_display?: string;
            /**
             * Seeders
             * @default 0
             */
            seeders?: number;
            /**
             * Leechers
             * @default 0
             */
            leechers?: number;
            /**
             * Times Completed
             * @default 0
             */
            times_completed?: number;
            /**
             * Discount
             * @default NORMAL
             */
            discount?: string;
            /** Douban */
            douban?: string | null;
            /** Imdb */
            imdb?: string | null;
            /** Douban Rating */
            douban_rating?: unknown | null;
            /** Imdb Rating */
            imdb_rating?: unknown | null;
            /** Description */
            description?: string | null;
        };
        /**
         * MediaWallRail
         * @description A horizontal Home media rail
         */
        MediaWallRail: {
            /**
             * Id
             * @enum {string}
             */
            id: "western_series" | "foreign_movies" | "asian_series" | "chinese_series" | "classic_restorations" | "quality_latest" | "popular_media";
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /** Items */
            items?: components["schemas"]["MediaWallItem"][];
        };
        /**
         * MediaWallResponse
         * @description Read-only cached Home media wall snapshot
         */
        MediaWallResponse: {
            /** Last Refreshed */
            last_refreshed?: string | null;
            /** Next Refresh */
            next_refresh?: string | null;
            /**
             * Stale
             * @default true
             */
            stale?: boolean;
            /**
             * Refresh Status
             * @default empty
             * @enum {string}
             */
            refresh_status?: "ok" | "empty" | "error";
            /** Last Error */
            last_error?: string | null;
            /** Rails */
            rails?: components["schemas"]["MediaWallRail"][];
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PanelAverageSpeeds
         * @description Average speeds calculated from local PANEL history
         */
        PanelAverageSpeeds: {
            /**
             * Upload 30Min
             * @default 0
             */
            upload_30min?: number;
            /**
             * Download 30Min
             * @default 0
             */
            download_30min?: number;
            /**
             * Upload Display
             * @default 0 B/s
             */
            upload_display?: string;
            /**
             * Download Display
             * @default 0 B/s
             */
            download_display?: string;
        };
        /**
         * PanelCollectorStatus
         * @description PANEL collector heartbeat exposed by /api/status
         */
        PanelCollectorStatus: {
            /** Last Started */
            last_started?: string | null;
            /** Last Success */
            last_success?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Last Duration Seconds */
            last_duration_seconds?: number | null;
            /** Next Refresh */
            next_refresh?: string | null;
            /** Heartbeat Age Seconds */
            heartbeat_age_seconds?: number | null;
            /**
             * Stale
             * @default false
             */
            stale?: boolean;
            /**
             * Stale After Seconds
             * @default 0
             */
            stale_after_seconds?: number;
        };
        /**
         * PanelDeleteTorrentsResponse
         * @description Batch delete response
         */
        PanelDeleteTorrentsResponse: {
            /** Success */
            success: boolean;
            /**
             * Deleted Count
             * @default 0
             */
            deleted_count?: number;
            /** Failed */
            failed?: string[];
            /** Error */
            error?: string | null;
        };
        /**
         * PanelHistoryResponse
         * @description PANEL traffic history response
         */
        PanelHistoryResponse: {
            /**
             * Range
             * @enum {string}
             */
            range: "1h" | "6h" | "12h" | "24h" | "7d" | "30d";
            /**
             * Aggregation
             * @default none
             */
            aggregation?: string;
            /** Data Points */
            data_points?: components["schemas"]["PanelTrafficDataPoint"][];
            /** Error */
            error?: string | null;
        };
        /**
         * PanelMetricPoint
         * @description Cumulative upload/download point
         */
        PanelMetricPoint: {
            /**
             * Uploaded
             * @default 0
             */
            uploaded?: number;
            /**
             * Downloaded
             * @default 0
             */
            downloaded?: number;
        };
        /**
         * PanelPauseTorrentsResponse
         * @description Batch pause response
         */
        PanelPauseTorrentsResponse: {
            /** Success */
            success: boolean;
            /**
             * Paused Count
             * @default 0
             */
            paused_count?: number;
            /** Failed */
            failed?: string[];
            /** Error */
            error?: string | null;
        };
        /**
         * PanelResumeTorrentsResponse
         * @description Batch resume response
         */
        PanelResumeTorrentsResponse: {
            /** Success */
            success: boolean;
            /**
             * Resumed Count
             * @default 0
             */
            resumed_count?: number;
            /** Failed */
            failed?: string[];
            /** Error */
            error?: string | null;
        };
        /**
         * PanelShareRatioDataPoint
         * @description Share-ratio history point
         */
        PanelShareRatioDataPoint: {
            /** Timestamp */
            timestamp: number;
            /**
             * Share Ratio
             * @default 0
             */
            share_ratio?: number;
        };
        /**
         * PanelShareRatioResponse
         * @description PANEL share-ratio history response
         */
        PanelShareRatioResponse: {
            /**
             * Range
             * @enum {string}
             */
            range: "1h" | "6h" | "12h" | "24h" | "7d" | "30d";
            /** Data Points */
            data_points?: components["schemas"]["PanelShareRatioDataPoint"][];
            /**
             * Current
             * @default 0
             */
            current?: number;
            /**
             * Highest
             * @default 0
             */
            highest?: number;
            /**
             * Lowest
             * @default 0
             */
            lowest?: number;
            /**
             * Change 24H
             * @default 0
             */
            change_24h?: number;
            /** Error */
            error?: string | null;
        };
        /**
         * PanelStatsResponse
         * @description PANEL stats response
         */
        PanelStatsResponse: {
            mteam?: components["schemas"]["PanelTrafficSummary"];
            qbittorrent?: components["schemas"]["PanelTrafficSummary"];
            user?: components["schemas"]["PanelUserSummary"];
            storage?: components["schemas"]["PanelStorageInfo"] | null;
            avg_speeds?: components["schemas"]["PanelAverageSpeeds"] | null;
            /** Last Update */
            last_update: number;
        };
        /**
         * PanelStorageInfo
         * @description qBittorrent storage summary
         */
        PanelStorageInfo: {
            /** Total */
            total?: number | null;
            /** Used */
            used?: number | null;
            /** Free */
            free?: number | null;
            /** Percent */
            percent?: number | null;
            /** Total Display */
            total_display?: string | null;
            /** Used Display */
            used_display?: string | null;
            /** Free Display */
            free_display?: string | null;
            /** Save Path */
            save_path?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * PanelTorrentHealth
         * @description PANEL torrent health summary
         */
        PanelTorrentHealth: {
            /**
             * Score
             * @default 0
             */
            score?: number;
            /**
             * Status
             * @default
             */
            status?: string;
            /**
             * Reason
             * @default
             */
            reason?: string;
        };
        /**
         * PanelTorrentItem
         * @description qBittorrent torrent item displayed by PANEL
         */
        PanelTorrentItem: {
            /** Id */
            id?: string | null;
            /**
             * Hash
             * @default
             */
            hash?: string;
            /**
             * Name
             * @default
             */
            name?: string;
            /**
             * Size
             * @default 0
             */
            size?: number;
            /**
             * Size Display
             * @default
             */
            size_display?: string;
            /**
             * Progress
             * @default 0
             */
            progress?: number;
            /**
             * Status
             * @default
             */
            status?: string;
            /** Tags */
            tags?: string[];
            /**
             * Ratio
             * @default 0
             */
            ratio?: number;
            /**
             * Uploaded
             * @default 0
             */
            uploaded?: number;
            /**
             * Downloaded
             * @default 0
             */
            downloaded?: number;
            /**
             * Upload Speed
             * @default 0
             */
            upload_speed?: number;
            /**
             * Download Speed
             * @default 0
             */
            download_speed?: number;
            /**
             * Seeders
             * @default 0
             */
            seeders?: number;
            /**
             * Leechers
             * @default 0
             */
            leechers?: number;
            /**
             * Added On
             * @default 0
             */
            added_on?: number;
            /** Eta */
            eta?: number | null;
            health?: components["schemas"]["PanelTorrentHealth"];
            /** Mteam Id */
            mteam_id?: string | null;
            /** Quality Metadata */
            quality_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PanelTorrentsResponse
         * @description PANEL torrent list response
         */
        PanelTorrentsResponse: {
            /** Torrents */
            torrents?: components["schemas"]["PanelTorrentItem"][];
            /**
             * Total Count
             * @default 0
             */
            total_count?: number;
            /**
             * Filtered Count
             * @default 0
             */
            filtered_count?: number;
            /** Error */
            error?: string | null;
        };
        /**
         * PanelTrafficDataPoint
         * @description Traffic history point
         */
        PanelTrafficDataPoint: {
            /** Timestamp */
            timestamp: number;
            mteam?: components["schemas"]["PanelMetricPoint"];
            qbittorrent?: components["schemas"]["PanelMetricPoint"];
        };
        /**
         * PanelTrafficSummary
         * @description Traffic summary for M-Team or qBittorrent counters
         */
        PanelTrafficSummary: {
            /**
             * Uploaded
             * @default 0
             */
            uploaded?: number;
            /**
             * Downloaded
             * @default 0
             */
            downloaded?: number;
            /** Uploaded Display */
            uploaded_display?: string | null;
            /** Downloaded Display */
            downloaded_display?: string | null;
            /**
             * Upload Speed
             * @default 0
             */
            upload_speed?: number;
            /**
             * Download Speed
             * @default 0
             */
            download_speed?: number;
        };
        /**
         * PanelUserSummary
         * @description User-level PANEL stats
         */
        PanelUserSummary: {
            /**
             * Share Ratio
             * @default 0
             */
            share_ratio?: number;
            /**
             * Uploaded
             * @default 0
             */
            uploaded?: number;
            /**
             * Downloaded
             * @default 0
             */
            downloaded?: number;
            /** Uploaded Display */
            uploaded_display?: string | null;
            /** Downloaded Display */
            downloaded_display?: string | null;
            /** Bonus */
            bonus?: number | null;
            /**
             * Seeding Count
             * @default 0
             */
            seeding_count?: number;
            /**
             * Leeching Count
             * @default 0
             */
            leeching_count?: number;
            /** User Level */
            user_level?: string | null;
        };
        /** PauseTorrentsRequest */
        PauseTorrentsRequest: {
            /** Hashes */
            hashes: string[];
        };
        /** ResumeTorrentsRequest */
        ResumeTorrentsRequest: {
            /** Hashes */
            hashes: string[];
        };
        /**
         * RuleConfig
         * @description Rule configuration for filtering and scoring torrents
         */
        RuleConfig: {
            /**
             * Min Size Gb
             * @default 20
             */
            min_size_gb?: number;
            /**
             * Max Size Gb
             * @default 500
             */
            max_size_gb?: number;
            /**
             * Discount Types
             * @default [
             *       "FREE",
             *       "_2X_FREE"
             *     ]
             */
            discount_types?: string[];
            /**
             * Include Keywords
             * @default []
             */
            include_keywords?: string[];
            /**
             * Exclude Keywords
             * @default [
             *       "AUDIOBOOK"
             *     ]
             */
            exclude_keywords?: string[];
            /**
             * Max Seeders
             * @default 10
             */
            max_seeders?: number;
            /**
             * Min Leechers
             * @default 100
             */
            min_leechers?: number;
            /**
             * Weight Size
             * @default -1
             */
            weight_size?: number;
            /**
             * Weight Free Time
             * @default 0.4
             */
            weight_free_time?: number;
            /**
             * Weight Age
             * @default 0.5
             */
            weight_age?: number;
            /**
             * Weight Seeders
             * @default 3
             */
            weight_seeders?: number;
        };
        /**
         * RuntimeConfigStatus
         * @description Non-secret runtime configuration summary
         */
        RuntimeConfigStatus: {
            /** Debug */
            debug: boolean;
            /** Refresh Interval Seconds */
            refresh_interval_seconds: number;
            /** Panel Collect Interval Seconds */
            panel_collect_interval_seconds: number;
            /**
             * Media Wall Refresh Interval Seconds
             * @default 0
             */
            media_wall_refresh_interval_seconds?: number;
            /**
             * Media Wall Startup Delay Seconds
             * @default 0
             */
            media_wall_startup_delay_seconds?: number;
            /**
             * Media Wall Source Stagger Seconds
             * @default 0
             */
            media_wall_source_stagger_seconds?: number;
            /**
             * Media Wall Douban Poster Fetches
             * @default 0
             */
            media_wall_douban_poster_fetches?: number;
            /** Api Delay Seconds */
            api_delay_seconds: number;
            /** Qbittorrent Configured */
            qbittorrent_configured: boolean;
            /** Mteam Token Configured */
            mteam_token_configured: boolean;
            /** Mteam User Configured */
            mteam_user_configured: boolean;
        };
        /**
         * SearchRequest
         * @description Request model for torrent search
         */
        SearchRequest: {
            /**
             * Keyword
             * @default
             */
            keyword?: string;
            /**
             * Mode
             * @default normal
             * @enum {string}
             */
            mode?: "normal" | "adult" | "movie" | "tvshow" | "other";
            /** Categories */
            categories?: number[];
            /** Standards */
            standards?: number[];
            /** Videocodecs */
            videoCodecs?: number[];
            /** Audiocodecs */
            audioCodecs?: number[];
            /** Sources */
            sources?: number[];
            /** Countries */
            countries?: number[];
            /**
             * Discount
             * @default
             */
            discount?: string;
            /**
             * Sortfield
             * @default CREATED_DATE
             */
            sortField?: string;
            /**
             * Sortdirection
             * @default DESC
             */
            sortDirection?: string;
            /**
             * Pagenumber
             * @default 1
             */
            pageNumber?: number;
            /**
             * Pagesize
             * @default 50
             */
            pageSize?: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_pilot_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_config_api_pilot_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomationConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_pilot_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dry_run_api_pilot_dry_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_download_api_pilot_run_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_cleanup_api_pilot_run_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_media_wall_api_home_media_wall_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaWallResponse"];
                };
            };
        };
    };
    get_panel_stats_api_panel_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelStatsResponse"];
                };
            };
        };
    };
    get_panel_history_api_panel_history_get: {
        parameters: {
            query?: {
                range?: "1h" | "6h" | "12h" | "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_panel_share_ratio_api_panel_share_ratio_get: {
        parameters: {
            query?: {
                range?: "1h" | "6h" | "12h" | "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelShareRatioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_panel_torrents_api_panel_torrents_get: {
        parameters: {
            query?: {
                tag?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelTorrentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_torrents_api_panel_torrents_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PauseTorrentsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelPauseTorrentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_torrents_api_panel_torrents_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeTorrentsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelResumeTorrentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_torrents_api_panel_torrents_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteTorrentsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelDeleteTorrentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_torrents_api_torrents_get: {
        parameters: {
            query?: {
                discount?: string;
                min_size?: number;
                max_size?: number;
                category?: string;
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_torrent_api_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_delete_toggle_api_auto_delete_toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoDeleteToggleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_delete_status_api_auto_delete_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    filter_options_api_filter_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    radar_api_radar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radar_download_api_radar_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiStatusResponse"];
                };
            };
        };
    };
}
